"""initial_schema

Revision ID: e9fc446ffb64
Revises: 
Create Date: 2026-01-27 15:34:50.913430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9fc446ffb64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.Enum('STRIPE', 'STRIPE_CONNECT', 'PAYPAL', 'PLAID', 'SQUARE', name='accountprovider'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'RESTRICTED', 'DISCONNECTED', name='accountstatus'), nullable=False),
    sa.Column('details_submitted', sa.Boolean(), nullable=True),
    sa.Column('charges_enabled', sa.Boolean(), nullable=True),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('account_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_account_id')
    )
    op.create_index(op.f('ix_connected_accounts_tenant_id'), 'connected_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTUP', 'PRO', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'INCOMPLETE', 'UNPAID', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('api_calls_used', sa.Integer(), nullable=False),
    sa.Column('api_calls_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('billing_period', sa.String(length=7), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_billing_period'), 'usage_records', ['billing_period'], unique=False)
    op.create_index(op.f('ix_usage_records_timestamp'), 'usage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index('ix_usage_user_endpoint', 'usage_records', ['user_id', 'endpoint'], unique=False)
    op.create_index('ix_usage_user_period', 'usage_records', ['user_id', 'billing_period'], unique=False)
    op.create_table('usage_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('billing_period', sa.String(length=7), nullable=False),
    sa.Column('total_api_calls', sa.Integer(), nullable=False),
    sa.Column('consents_created', sa.Integer(), nullable=False),
    sa.Column('authorizations_created', sa.Integer(), nullable=False),
    sa.Column('verifications_performed', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('first_call_at', sa.DateTime(), nullable=True),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summary_user_period', 'usage_summaries', ['user_id', 'billing_period'], unique=True)
    op.create_index(op.f('ix_usage_summaries_billing_period'), 'usage_summaries', ['billing_period'], unique=False)
    op.create_index(op.f('ix_usage_summaries_user_id'), 'usage_summaries', ['user_id'], unique=False)
    op.create_table('agent_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('authorization_id', sa.String(length=36), nullable=True),
    sa.Column('consent_id', sa.String(length=36), nullable=True),
    sa.Column('connected_account_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.Enum('STRIPE', 'STRIPE_CONNECT', 'PAYPAL', 'PLAID', 'SQUARE', name='accountprovider'), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_category', sa.String(length=100), nullable=True),
    sa.Column('authorization_status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorizations.id'], ),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_transactions_agent_id'), 'agent_transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_transactions_provider_transaction_id'), 'agent_transactions', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_agent_transactions_tenant_id'), 'agent_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_transactions_user_id'), 'agent_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_authorizations_developer_id'), 'authorizations', ['developer_id'], unique=False)
    op.create_index(op.f('ix_consents_developer_id'), 'consents', ['developer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_developer_id'), table_name='consents')
    op.drop_index(op.f('ix_authorizations_developer_id'), table_name='authorizations')
    op.drop_index(op.f('ix_agent_transactions_user_id'), table_name='agent_transactions')
    op.drop_index(op.f('ix_agent_transactions_tenant_id'), table_name='agent_transactions')
    op.drop_index(op.f('ix_agent_transactions_provider_transaction_id'), table_name='agent_transactions')
    op.drop_index(op.f('ix_agent_transactions_agent_id'), table_name='agent_transactions')
    op.drop_table('agent_transactions')
    op.drop_index(op.f('ix_usage_summaries_user_id'), table_name='usage_summaries')
    op.drop_index(op.f('ix_usage_summaries_billing_period'), table_name='usage_summaries')
    op.drop_index('ix_summary_user_period', table_name='usage_summaries')
    op.drop_table('usage_summaries')
    op.drop_index('ix_usage_user_period', table_name='usage_records')
    op.drop_index('ix_usage_user_endpoint', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_timestamp'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_billing_period'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_tenant_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
